### ISSUE TITLE
Bug/Feature : Support for caelus api/elytra slot

### ISSUE THREAD

**Issue by Blugori** [infernalstudios/Elytra-Bounce#2]
That's it, from my tests you can't bounce when the elytra is in a curios slot
Support would be nice ! The bouncing mecanic is really satisfying !

**Comment by nekomaster1000** [comment]
Hiya! We looked into this, but have no idea how to integrate this compatibility, so we won't be pursuing it further. Won't be fixing this one without assistance. Sorry!
